### ISSUE TITLE
(Destar) !feedback !lobby<Size> <Lobby Name> command

U...

### ISSUE THREAD

**Issue by Kryzoid** [Kryzoid/botzoid-feedback#4]
**Server:** LEGM
**Channel:** bot
**User:** Kryzoid#3569

**Message:**
(Destar) !feedback !lobby<Size> <Lobby Name> command

User would type !lobby followed immediately by a number for the size of the lobby (max limit 10) and then a space followed by a string, this would create a lobby object for a period of time that people can join and leave using reactions. Would be useful for organizing games, viewing parties and funny joke lobbies.

Example: I would type

!lobby8 L4D2

and it would display the following message

Destar has created a lobby for L4D2
Lobby State: Active

Current Members
▶ Destar

There are 7 slots remaining.
➕ ➖ 

If Mongo clicked the plus it would change to

Destar has created a lobby for L4D2
Lobby State: Active

Current Members
▶ Destar
▶ Mongo

There are 7 slots remaining.

Clicking the minus would leave the lobby and !closeLobby or some similar command would close whatever lobby you currently have open

`Filed on 7/21/17 9:53:11 PM using Discord.NET 1.0.0-rc2.`

**Comment by Ryan-King** [comment]
Wrote some stub for an !event idea https://pastebin.com/raw/Nqn6LJq5

**Comment by Kryzoid** [comment]
Actually probably not going to do this one - too much work for little gain
